### PR TITLE
Add 6.2-rc support

### PR DESCRIPTION
**Pull request by timocapa**
I wasn't sure what kernels to allow this on, sorry :( 

Patch will break kernels prior to 6.2, in case of systems with multiple kernel versions installed

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Thanks timocapa! I cannot test it currently, so I'll believe in you :frog: :heart:

**Comment by timocapa** [comment]
It's fine for me, at least.

> timo@mauve ~> uname -r; nvidia-smi|rg -i "Driver Version"
6.2.0-rc1-273-tkg-bore-llvm
| NVIDIA-SMI 525.60.11    Driver Version: 525.60.11    CUDA Version: 12.0     |

**Comment by anonish** [comment]
using the patch does break kernels other than 6.2.

using this patch here:
https://gist.github.com/joanbm/963906fc6772d8955faf1b9cc46c6b04#file-nvidia-470xx-fix-linux-6-2-patch

and removing the nvidia-acpi stuff (everything after line 84 on the above starting with "
diff --git a/nvidia/nv-acpi.c b/nvidia/nv-acpi.c" )as described here:
http://rglinuxtech.com/?p=3085

will work without breaking other kernels (at least for me it built the nvidia vulkan beta driver 525.47.04 for kernels 6.0.12, 6.2.0-rc1 and 6.1.0)

**Comment by ptr1337** [comment]
https://github.com/Frogging-Family/nvidia-all/pull/139

I already sent a PR which fixes it. Just waiting to be merged.
Tested and it works.

**Comment by timocapa** [comment]
> #139
> 
> I already sent a PR which fixes it. Just waiting to be merged. Tested and it works.

Dammit you were faster than me at replying

**Pull request merged**
