### PR TITLE
Add support for vulkan dev 525.47.31

### PR DESCRIPTION
**Pull request by notpentadactyl**
> Vulkan Beta Driver Release Updates
> July 11th, 2023 - Windows 532.28, Linux 525.47.31
> 
> New:
> VK_KHR_cooperative_matrix
> VK_EXT_depth_bias_control
> VK_EXT_dynamic_rendering_unused_attachments
> VK_MESA_video_decode_av1 preliminary implementation for Ada GPUs
> VK_NV_displacement_micromap updated to version 2
> Vulkan video updates:
> VK_KHR_video_encode_queue version update 8->9
> VK_EXT_video_encode_h264 version update 10->11
> Fixes:
> Fix for VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT
> Fix 64-bit shader disk cache issues

https://developer.nvidia.com/vulkan-driver

### CODE REVIEW

**Comment by qumaciel** [comment]
Hi, @notpentadactyl !
Can you also bump pkgrel from 247 -> 248?

**Comment by ryanmusante** [comment]
Are the vulkan drivers like a hybrid between beta and regular?

**Comment by qumaciel** [comment]
Hi, @ryanmusante ! No, it is a different branch, where they enable lots of provisional Vulkan extensions before putting them on beta/regular. 

It is a good choice in case you are using bleeding edge DXVK/VK3D or testing vulkan video.

**Comment by notpentadactyl** [comment]
> Hi, @notpentadactyl ! Can you also bump pkgrel from 247 -> 248?

is there really a reason for it?

**Pull request closed without merging**
