### PR TITLE
Add initial kernel 5.11 patch

### PR DESCRIPTION
**Pull request by Snoop05**
tested on 5.11rc2 + 460.32.03

http://rglinuxtech.com/?p=2878
http://rglinuxtech.com/?p=2871

### CODE REVIEW

**Comment by Snoop05** [comment]
Should fixes for older (/beta) kernel versions be added too?

**Comment by anonish** [comment]
please see
https://github.com/Frogging-Family/nvidia-all/issues/26

when function vercmp on my archlinux linux-git or linux-amd-git kernels, the version comes out to 5.10.0-rc3 (instead of 5.11-rc3) so it fails the test for :
vercmp "$_kernel" "5.11"

the package names do show 5.11:
linux-amd-git-5.11.968815.a135a1b4c4db-1

not sure if it's something i'm doing or if this is normal

**Comment by Snoop05** [comment]
In such case it is possible to force applying patches in [configuration.cfg](https://github.com/Frogging-Family/nvidia-all/blob/b3a6379dbbcbfc59f8c0bbe3f0b4098c86dafa92/customization.cfg#L16)

**Comment by Tk-Glitch** [comment]
Sorry for the delay, I would have liked to test it before merging. I won't be able to for an undetermined amount of time so.. Let's give it a whirl.

**Comment by Ross-Carran** [comment]
http://rglinuxtech.com/?p=2881
With patch included fails many hunks.
Without patch works with 5.11rc5
With driver 460.39 the patch no longer seems to be needed.
Tested for a little while, about 3 hours with games, so far no problems.

**Pull request merged**
