### PR TITLE
515.65.01

### PR DESCRIPTION
**Pull request by pongo1231**
https://www.nvidia.com/download/driverResults.aspx/191975/

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Thank you pongo1231! :frog: :heart:

**Comment by TechXero** [comment]
There's also [470.141.03](https://www.nvidia.com/download/driverResults.aspx/191232/en-us/)

thanks ;)

**Comment by Iglu47** [comment]
please, add 390 too
`515.65.01`  https://www.nvidia.com/Download/driverResults.aspx/191961/en-us
`470.141.03` https://www.nvidia.com/Download/driverResults.aspx/191232/en-us
`390.154` https://www.nvidia.com/Download/driverResults.aspx/191118/en-us

**Comment by Tk-Glitch** [comment]
We simply don't support 390 (and it's not worth the trouble as the GPUs not supported in newer revisions don't have vulkan support anyway).
I'll gladly add 470.141.03 though.

**Pull request merged**
